version: 2.1

# orbs:
#   aws-ecr: circleci/aws-ecr@x.y.z
jobs:
  build:
    docker:
      # - image: cimg/base:stable
      - image: docker:20.10.14-git
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache \
              py-pip=9.0.0-r1
            pip install \
              awscli==1.11.76
            # apk add --no-cache \
            #   python3 \
            #   py3-pip
            # pip3 install \
            #   awscliv2
      - run:
          name: "Docker build"
          command: |
            # Set unique-ish namespace
            NAMESPACE=$(whoami)

            export COMMIT_ID=$(git rev-parse --verify --short HEAD)
            echo commit ID is $COMMIT_ID

            aws ecr get-login-password \
              --profile at-interviews \
              --region us-west-2 \
              | docker login \
              --username AWS \
              --password-stdin \
              ${AWS_ACCOUNT_ID}.dkr.ecr.us-west-2.amazonaws.com
            
              docker build \
                --no-cache \
                --build-arg GIT_COMMIT=$COMMIT_ID \
                -t helloworld:$COMMIT_ID \
                -t ${AWS_ACCOUNT_ID}.dkr.ecr.us-west-2.amazonaws.com/helloworld:${COMMIT_ID} \
                .
              
              docker push \
                ${AWS_ACCOUNT_ID}.dkr.ecr.us-west-2.amazonaws.com/helloworld:${COMMIT_ID}



workflows:
  build-deploy-workflow:
    jobs:
      - build
